# run: conda env create --file environment.yml
name: base-binder-env
channels:
  - conda-forge
  - defaults
dependencies:
  - cmake
  - lxml
  - numpy >=1.18
  - python >=3.8
  - pandas
  - pip
  - scipy
  - pip:
    - black
    - isort
    - jupyterlab_code_formatter
    - nbgitpuller
