# run: conda env create --file environment.yml
name: scivis-binder-env
channels:
  - conda-forge
  - defaults
dependencies:
  - cmake
  - lxml
  - nodejs
  - numpy >=1.18  
  - python >=3.7
  - scipy
  - vtk
  # Extra
  - bokeh
  - imageio
  - imageio-ffmpeg
  - ipycanvas
  - ipyevents
  - ipympl
  - ipyvtklink
  - ipywidgets >=7.5
  - itkwidgets >=0.32
  - jupyter_bokeh
  - jupyterlab >=2.2.9
  - jupyterlab_widgets
  - matplotlib
  - pandas
  - pip
  - pyembree
  - pyvista >=0.27
  - seaborn
  - pip:
    - black
    - cmocean
    - colorcet
    - isort
    - jupyterlab_code_formatter
    - nbgitpuller
    - openmesh
    - pyct
    - rtree
    - tqdm
    - trimesh
