# run: conda env create --file environment.yml
name: binder-coda-environment
channels:
  - conda-forge
dependencies:
  - cmake
  - lxml
  - numpy >=1.18
  - python >=3.8
  - scipy
  - pip:
    - black
    - bokeh
    - cmocean
    - colorcet
    - imageio>=2.5.0
    - imageio-ffmpeg
    - ipycanvas
    - ipympl
    - ipywidgets
    - ipyvtk-simple
    - isort
    - itkwidgets
    - jupyter_bokeh
    - jupyterlab_code_formatter
    - matplotlib
    - nbgitpuller
    - openmesh
    - pandas
    - pyct
    - pyvista
    - seaborn
