# run: conda env create --file environment.yml
name: binder-coda-environment
channels:
  - conda-forge
  - defaults
dependencies:
  - cmake
  - lxml
  - nodejs
  - numpy >=1.18  
  - python >=3.7
  - scipy
  - vtk
  # Extra
  - bokeh
  - imageio
  - imageio-ffmpeg
  - ipycanvas
  - ipyevents
  - ipympl
  - ipyvtklink
  - ipywidgets
  - itkwidgets  
  - jupyter_bokeh
  - matplotlib
  - pandas
  - pyembree
  - pyvista
  - seaborn
  - pip:
    - black
    - cmocean
    - colorcet
    - ipyvtk-simple
    - isort
    - jupyterlab_code_formatter
    - nbgitpuller
    - openmesh
    - pyct
    - rtree
    - tqdm
    - trimesh
