# run: conda env create --file environment.yml
name: binder-coda-environment
channels:
  - conda-forge
dependencies:
  - cmake
  - lxml
  - numpy >=1.18
  - python >=3.8
  - scipy
  # Extra
  - bokeh
  - ipympl
  - ipywidgets
  - itkwidgets
  - jupyter_bokeh
  - matplotlib
  - pandas
  - pyvista
  - seaborn
  - pip:
    - black
    - cmocean
    - colorcet
    - imageio
    - imageio-ffmpeg
    - ipycanvas
    - ipyvtk-simple
    - isort
    - jupyterlab_code_formatter
    - nbgitpuller
    - openmesh
    - pyct
