# run: conda env create --file environment.yml
name: binder-coda-environment
channels:
  - conda-forge
dependencies:
  - python >=3.8
  - cmake
  - numpy >=1.18
  - scipy
  - jupyterlab_code_formatter
  - pip:
    - nbgitpuller
    - black
    - isort
